version: "3.8"

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - session:/app/session
      - media:/app/session/media
    restart: unless-stopped

volumes:
  media:
  session:
